### ISSUE TITLE
vecmath.h

### ISSUE THREAD

**Issue by mtrofin** [mtrofin/wasm-android-demo#12]
https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/common/vecmath.h#L202

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/common/vecmath.h#L400

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/common/vecmath.h#L805

remove comment

**Comment by njuwangchen** [comment]
done
