### ISSUE TITLE
MoreTeapotsNativeActivity.cpp - please remove commented code

### ISSUE THREAD

**Issue by mtrofin** [mtrofin/wasm-android-demo#17]
https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L64

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L69

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L165

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L177

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L198

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L198

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L352

https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/jni/MoreTeapotsNativeActivity.cpp#L421

**Comment by njuwangchen** [comment]
done
