### ISSUE TITLE
MoreTeapotsRenderer.cpp

### ISSUE THREAD

**Issue by mtrofin** [mtrofin/wasm-android-demo#4]
https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/common/MoreTeapotsRenderer.cpp#L33

Instead of the many #if checks, consider an alternative for ensuring exactly only one option is enabled. You could sum up the presence of each option, and ensure it adds up to 1, for instance.

**Comment by mtrofin** [comment]
https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/common/MoreTeapotsRenderer.cpp#L90

Remove comments

**Comment by mtrofin** [comment]
https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/common/MoreTeapotsRenderer.cpp#L597

Remove comments

**Comment by mtrofin** [comment]
https://github.com/mtrofin/wasm-android-demo/blob/master/app/src/main/common/MoreTeapotsRenderer.cpp#L82

This line and elsewhere, it looks like we're doing quite a bit of GL3-specific stuff. Should we simply pre-require GL3, and avoid the #ifdef then?

**Comment by njuwangchen** [comment]
No, I don't think we should pre-define GL3. For GL3 uses instancing and is not supported by GL2. Actually, I didn't use any GL3 stuff in my experiment. If you think too many #ifdef GL3 stuff is confusing, I think we can just delete all of GL3 stuff.

Also, another issue is that if I use the counter to check the number of defined macros, the compiler gives me a "duplicate declaration for global variable" error.

**Comment by njuwangchen** [comment]
done
